// Comprehensive list of genes for ortholog analysis
// Each gene includes category and description
// Alphabetically sorted to prevent duplicates

export const genes = {
  "ABCA4": { category: "Vision", description: "ATP-binding cassette transporter, retinal disease" },
  "ABO": { category: "Blood", description: "ABO blood group transferase" },
  "ACACA": { category: "Metabolism", description: "Acetyl-CoA carboxylase alpha, fatty acid synthesis" },
  "ACADL": { category: "Metabolism", description: "Acyl-CoA dehydrogenase long chain" },
  "ACADM": { category: "Metabolism", description: "Acyl-CoA dehydrogenase medium chain" },
  "ACADS": { category: "Metabolism", description: "Acyl-CoA dehydrogenase short chain" },
  "ACADVL": { category: "Metabolism", description: "Acyl-CoA dehydrogenase very long chain" },
  "ACE": { category: "Cardiovascular", description: "Angiotensin-converting enzyme" },
  "ACE2": { category: "Immune", description: "Angiotensin-converting enzyme 2, SARS-CoV-2 receptor" },
  "ACLY": { category: "Metabolism", description: "ATP citrate lyase" },
  "ACO2": { category: "Metabolism", description: "Aconitase 2, TCA cycle" },
  "ACOX1": { category: "Metabolism", description: "Acyl-CoA oxidase 1, fatty acid oxidation" },
  "ACSL1": { category: "Metabolism", description: "Acyl-CoA synthetase long chain 1" },
  "ACTB": { category: "Housekeeping", description: "Beta-actin, cytoskeleton" },
  "ACTG1": { category: "Housekeeping", description: "Gamma-actin, cytoskeleton" },
  "ACTN2": { category: "Muscle", description: "Alpha-actinin 2, muscle structure" },
  "AKT1": { category: "Signaling", description: "AKT serine/threonine kinase 1, PI3K pathway" },
  "ALDH2": { category: "Metabolism", description: "Aldehyde dehydrogenase 2, alcohol metabolism" },
  "ALDOA": { category: "Metabolism", description: "Aldolase A, glycolysis" },
  "ALDOB": { category: "Metabolism", description: "Aldolase B, fructose metabolism" },
  "ALK": { category: "Cancer", description: "Anaplastic lymphoma kinase, oncogene" },
  "APC": { category: "Cancer", description: "Adenomatous polyposis coli, tumor suppressor" },
  "APEX1": { category: "DNA Repair", description: "Apurinic/apyrimidinic endodeoxyribonuclease 1" },
  "APOB": { category: "Cardiovascular", description: "Apolipoprotein B, lipid transport" },
  "APOE": { category: "Neurological", description: "Apolipoprotein E, Alzheimer's risk factor" },
  "APP": { category: "Neurological", description: "Amyloid precursor protein, Alzheimer's disease" },
  "ARF1": { category: "Signaling", description: "ADP ribosylation factor 1, small GTPase" },
  "ARF6": { category: "Signaling", description: "ADP ribosylation factor 6, membrane trafficking" },
  "ARFGEF1": { category: "Signaling", description: "ARF guanine nucleotide exchange factor 1" },
  "ARHGAP11A": { category: "Neurodevelopment", description: "Rho GTPase activating protein, brain evolution" },
  "ARID1A": { category: "Epigenetic", description: "AT-rich interaction domain 1A, chromatin remodeling" },
  "ATG5": { category: "Autophagy", description: "Autophagy related 5" },
  "ATM": { category: "DNA Repair", description: "Ataxia telangiectasia mutated, DNA damage response" },
  "ATP5F1A": { category: "Metabolism", description: "ATP synthase F1 subunit alpha" },
  "ATRX": { category: "Epigenetic", description: "ATRX chromatin remodeler" },
  "AXIN1": { category: "Signaling", description: "Axin 1, WNT pathway" },
  "B2M": { category: "Immune", description: "Beta-2-microglobulin, MHC class I component" },
  "BAX": { category: "Apoptosis", description: "BCL2 associated X protein, pro-apoptotic" },
  "BCL2": { category: "Apoptosis", description: "B-cell lymphoma 2, anti-apoptotic" },
  "BDNF": { category: "Neurodevelopment", description: "Brain-derived neurotrophic factor" },
  "BECN1": { category: "Autophagy", description: "Beclin 1, autophagy initiator" },
  "BMP2": { category: "Development", description: "Bone morphogenetic protein 2" },
  "BMP4": { category: "Development", description: "Bone morphogenetic protein 4" },
  "BMPR1A": { category: "Development", description: "BMP receptor type 1A" },
  "BRAF": { category: "Cancer", description: "B-Raf proto-oncogene, MAPK pathway" },
  "BTK": { category: "Immune", description: "Bruton tyrosine kinase, B-cell development" },
  "C1QA": { category: "Immune", description: "Complement C1q A chain" },
  "C3": { category: "Immune", description: "Complement component 3" },
  "C5": { category: "Immune", description: "Complement component 5" },
  "CASP3": { category: "Apoptosis", description: "Caspase 3, executioner caspase" },
  "CCL19": { category: "Immune", description: "C-C motif chemokine ligand 19, lymphoid tissue" },
  "CCL2": { category: "Immune", description: "C-C motif chemokine ligand 2, monocyte chemoattractant" },
  "CCL3": { category: "Immune", description: "C-C motif chemokine ligand 3, MIP-1 alpha" },
  "CCL4": { category: "Immune", description: "C-C motif chemokine ligand 4, MIP-1 beta" },
  "CCL5": { category: "Immune", description: "C-C motif chemokine ligand 5, RANTES" },
  "CCND1": { category: "Cell Cycle", description: "Cyclin D1, cell cycle progression" },
  "CCNE1": { category: "Cell Cycle", description: "Cyclin E1, G1/S transition" },
  "CCR5": { category: "Immune", description: "C-C motif chemokine receptor 5, HIV co-receptor" },
  "CD19": { category: "Immune", description: "CD19 B-cell surface marker" },
  "CD22": { category: "Immune", description: "CD22 B-cell surface marker" },
  "CD274": { category: "Immune", description: "PD-L1, immune checkpoint ligand" },
  "CD28": { category: "Immune", description: "CD28 T-cell co-stimulator" },
  "CD3D": { category: "Immune", description: "CD3 delta, T-cell receptor complex" },
  "CD3E": { category: "Immune", description: "CD3 epsilon, T-cell receptor complex" },
  "CD3G": { category: "Immune", description: "CD3 gamma, T-cell receptor complex" },
  "CD40": { category: "Immune", description: "CD40 TNF receptor, B-cell activation" },
  "CD40LG": { category: "Immune", description: "CD40 ligand, T-cell helper signal" },
  "CD80": { category: "Immune", description: "CD80 B7-1, T-cell co-stimulation" },
  "CD86": { category: "Immune", description: "CD86 B7-2, T-cell co-stimulation" },
  "CD8A": { category: "Immune", description: "CD8 alpha, T-cell surface glycoprotein" },
  "CDC42": { category: "Signaling", description: "Cell division cycle 42, Rho GTPase" },
  "CDH1": { category: "Cell Adhesion", description: "E-cadherin, epithelial adhesion" },
  "CDK2": { category: "Cell Cycle", description: "Cyclin-dependent kinase 2" },
  "CDK4": { category: "Cell Cycle", description: "Cyclin-dependent kinase 4" },
  "CDK6": { category: "Cell Cycle", description: "Cyclin-dependent kinase 6" },
  "CDKN1A": { category: "Cell Cycle", description: "Cyclin-dependent kinase inhibitor 1A, p21" },
  "CDKN1B": { category: "Cell Cycle", description: "Cyclin-dependent kinase inhibitor 1B, p27" },
  "CDKN2B": { category: "Cell Cycle", description: "Cyclin-dependent kinase inhibitor 2B, p15" },
  "CDKN2C": { category: "Cell Cycle", description: "Cyclin-dependent kinase inhibitor 2C, p18" },
  "CDKN2D": { category: "Cell Cycle", description: "Cyclin-dependent kinase inhibitor 2D, p19" },
  "CFH": { category: "Immune", description: "Complement factor H, regulator" },
  "CFTR": { category: "Channel", description: "Cystic fibrosis transmembrane conductance regulator" },
  "CHEK1": { category: "DNA Repair", description: "Checkpoint kinase 1, cell cycle arrest" },
  "CHEK2": { category: "DNA Repair", description: "Checkpoint kinase 2, DNA damage response" },
  "CHUK": { category: "Signaling", description: "Component of IKK complex, NF-kB pathway" },
  "CNTNAP2": { category: "Neurodevelopment", description: "Contactin associated protein 2, autism, language" },
  "COL1A1": { category: "Extracellular Matrix", description: "Collagen type I alpha 1 chain" },
  "COLEC11": { category: "Immune", description: "Collectin subfamily member 11, complement" },
  "COMT": { category: "Neurotransmitter", description: "Catechol-O-methyltransferase, dopamine metabolism" },
  "COX4I1": { category: "Metabolism", description: "Cytochrome c oxidase subunit 4I1, electron transport" },
  "CPT1A": { category: "Metabolism", description: "Carnitine palmitoyltransferase 1A, fatty acid oxidation" },
  "CPT2": { category: "Metabolism", description: "Carnitine palmitoyltransferase 2, mitochondrial" },
  "CREBBP": { category: "Epigenetic", description: "CREB binding protein, histone acetyltransferase" },
  "CS": { category: "Metabolism", description: "Citrate synthase, TCA cycle" },
  "CSF1R": { category: "Signaling", description: "Colony stimulating factor 1 receptor, macrophages" },
  "CSF3": { category: "Immune", description: "Colony stimulating factor 3, G-CSF" },
  "CTLA4": { category: "Immune", description: "Cytotoxic T-lymphocyte associated protein 4, checkpoint" },
  "CTNNB1": { category: "Signaling", description: "Beta-catenin, WNT pathway" },
  "CXCL10": { category: "Immune", description: "C-X-C motif chemokine ligand 10, IP-10" },
  "CXCL12": { category: "Immune", description: "C-X-C motif chemokine ligand 12, SDF-1" },
  "CXCR4": { category: "Immune", description: "C-X-C motif chemokine receptor 4, stem cell homing" },
  "CYCS": { category: "Apoptosis", description: "Cytochrome c, apoptosis trigger" },
  "DAXX": { category: "Epigenetic", description: "Death domain associated protein, histone chaperone" },
  "DHCR24": { category: "Metabolism", description: "24-dehydrocholesterol reductase" },
  "DHCR7": { category: "Metabolism", description: "7-dehydrocholesterol reductase, cholesterol synthesis" },
  "DISC1": { category: "Neurodevelopment", description: "Disrupted in schizophrenia 1" },
  "DKK1": { category: "Signaling", description: "Dickkopf WNT signaling pathway inhibitor 1" },
  "DMD": { category: "Muscle", description: "Dystrophin, muscular dystrophy" },
  "DNMT1": { category: "Epigenetic", description: "DNA methyltransferase 1, maintenance methylation" },
  "DNMT3A": { category: "Epigenetic", description: "DNA methyltransferase 3A, de novo methylation" },
  "DRD2": { category: "Neurotransmitter", description: "Dopamine receptor D2" },
  "DRD4": { category: "Neurotransmitter", description: "Dopamine receptor D4" },
  "E2F1": { category: "Cell Cycle", description: "E2F transcription factor 1, cell cycle control" },
  "E2F3": { category: "Cell Cycle", description: "E2F transcription factor 3" },
  "EEF1A1": { category: "Housekeeping", description: "Eukaryotic translation elongation factor 1 alpha 1" },
  "EEF2": { category: "Housekeeping", description: "Eukaryotic translation elongation factor 2" },
  "EGFR": { category: "Signaling", description: "Epidermal growth factor receptor, RTK" },
  "ENO1": { category: "Metabolism", description: "Enolase 1, glycolysis" },
  "ENO2": { category: "Metabolism", description: "Enolase 2, neuron-specific" },
  "ENO3": { category: "Metabolism", description: "Enolase 3, muscle-specific" },
  "EP300": { category: "Epigenetic", description: "E1A binding protein p300, histone acetyltransferase" },
  "EPAS1": { category: "Signaling", description: "Endothelial PAS domain protein 1, HIF-2 alpha" },
  "ERBB2": { category: "Cancer", description: "Erb-b2 receptor tyrosine kinase 2, HER2" },
  "ERBB3": { category: "Signaling", description: "Erb-b2 receptor tyrosine kinase 3, HER3" },
  "ERBB4": { category: "Signaling", description: "Erb-b2 receptor tyrosine kinase 4, HER4" },
  "ERCC2": { category: "DNA Repair", description: "Excision repair cross-complementing 2, helicase" },
  "ESR1": { category: "Hormone", description: "Estrogen receptor 1" },
  "EZH2": { category: "Epigenetic", description: "Enhancer of zeste homolog 2, histone methyltransferase" },
  "FANCA": { category: "DNA Repair", description: "Fanconi anemia complementation group A" },
  "FASN": { category: "Metabolism", description: "Fatty acid synthase" },
  "FCGR3A": { category: "Immune", description: "Fc gamma receptor 3A, NK cell marker" },
  "FDFT1": { category: "Metabolism", description: "Farnesyl-diphosphate farnesyltransferase 1, cholesterol" },
  "FDPS": { category: "Metabolism", description: "Farnesyl diphosphate synthase" },
  "FGFR1": { category: "Signaling", description: "Fibroblast growth factor receptor 1" },
  "FGFR2": { category: "Signaling", description: "Fibroblast growth factor receptor 2" },
  "FGFR3": { category: "Signaling", description: "Fibroblast growth factor receptor 3" },
  "FGFR4": { category: "Signaling", description: "Fibroblast growth factor receptor 4" },
  "FLCN": { category: "Cancer", description: "Folliculin, tumor suppressor" },
  "FMR1": { category: "Neurodevelopment", description: "Fragile X mental retardation 1" },
  "FN1": { category: "Extracellular Matrix", description: "Fibronectin 1" },
  "FOXP2": { category: "Neurodevelopment", description: "Forkhead box P2, speech and language" },
  "FOXP3": { category: "Immune", description: "Forkhead box P3, regulatory T-cells" },
  "FYN": { category: "Signaling", description: "FYN proto-oncogene, Src family kinase" },
  "FZD1": { category: "Signaling", description: "Frizzled class receptor 1, WNT receptor" },
  "GABRG2": { category: "Neurotransmitter", description: "GABA A receptor gamma 2 subunit" },
  "GAPDH": { category: "Housekeeping", description: "Glyceraldehyde-3-phosphate dehydrogenase, glycolysis" },
  "GAPDHS": { category: "Metabolism", description: "Glyceraldehyde-3-phosphate dehydrogenase, spermatogenic" },
  "GATA4": { category: "Development", description: "GATA binding protein 4, heart development" },
  "GH1": { category: "Hormone", description: "Growth hormone 1" },
  "GNB1": { category: "Signaling", description: "G protein subunit beta 1" },
  "GPI": { category: "Metabolism", description: "Glucose-6-phosphate isomerase, glycolysis" },
  "GRB2": { category: "Signaling", description: "Growth factor receptor bound protein 2, adaptor" },
  "GREM1": { category: "Development", description: "Gremlin 1, BMP antagonist" },
  "GRIN1": { category: "Neurotransmitter", description: "Glutamate ionotropic receptor NMDA type subunit 1" },
  "GSK3B": { category: "Signaling", description: "Glycogen synthase kinase 3 beta, WNT pathway" },
  "H2AFZ": { category: "Housekeeping", description: "H2A.Z histone variant" },
  "H2AX": { category: "DNA Repair", description: "H2A.X histone variant, DNA damage marker" },
  "HADHA": { category: "Metabolism", description: "Hydroxyacyl-CoA dehydrogenase subunit alpha" },
  "HADHB": { category: "Metabolism", description: "Hydroxyacyl-CoA dehydrogenase subunit beta" },
  "HDAC1": { category: "Epigenetic", description: "Histone deacetylase 1" },
  "HDAC2": { category: "Epigenetic", description: "Histone deacetylase 2" },
  "HDAC3": { category: "Epigenetic", description: "Histone deacetylase 3" },
  "HIF1A": { category: "Signaling", description: "Hypoxia inducible factor 1 alpha" },
  "HMGCR": { category: "Metabolism", description: "HMG-CoA reductase, cholesterol synthesis" },
  "HMGCS1": { category: "Metabolism", description: "HMG-CoA synthase 1" },
  "HNRNPA1": { category: "Housekeeping", description: "Heterogeneous nuclear ribonucleoprotein A1" },
  "HOXA1": { category: "Development", description: "Homeobox A1, hindbrain development" },
  "HOXD13": { category: "Development", description: "Homeobox D13, limb development" },
  "HRAS": { category: "Signaling", description: "Harvey rat sarcoma viral oncogene, small GTPase" },
  "HSPA8": { category: "Housekeeping", description: "Heat shock protein family A member 8, HSC70" },
  "HTR2A": { category: "Neurotransmitter", description: "5-hydroxytryptamine receptor 2A, serotonin" },
  "ICOS": { category: "Immune", description: "Inducible T-cell co-stimulator" },
  "IDH1": { category: "Metabolism", description: "Isocitrate dehydrogenase 1, cytosolic" },
  "IDH2": { category: "Metabolism", description: "Isocitrate dehydrogenase 2, mitochondrial" },
  "IDH3A": { category: "Metabolism", description: "Isocitrate dehydrogenase 3 alpha, TCA cycle" },
  "IGF1": { category: "Signaling", description: "Insulin-like growth factor 1" },
  "IGF1R": { category: "Signaling", description: "Insulin-like growth factor 1 receptor" },
  "IGF2": { category: "Signaling", description: "Insulin-like growth factor 2" },
  "IKBKB": { category: "Signaling", description: "Inhibitor of kB kinase beta, NF-kB pathway" },
  "IL10": { category: "Immune", description: "Interleukin 10, anti-inflammatory cytokine" },
  "IL12A": { category: "Immune", description: "Interleukin 12A, p35 subunit" },
  "IL12B": { category: "Immune", description: "Interleukin 12B, p40 subunit" },
  "IL13": { category: "Immune", description: "Interleukin 13, Th2 cytokine" },
  "IL15": { category: "Immune", description: "Interleukin 15, NK/T-cell factor" },
  "IL1B": { category: "Immune", description: "Interleukin 1 beta, inflammatory cytokine" },
  "IL21": { category: "Immune", description: "Interleukin 21, T-cell factor" },
  "IL22": { category: "Immune", description: "Interleukin 22, epithelial immunity" },
  "IL23A": { category: "Immune", description: "Interleukin 23A, p19 subunit" },
  "IRS1": { category: "Signaling", description: "Insulin receptor substrate 1" },
  "IRS2": { category: "Signaling", description: "Insulin receptor substrate 2" },
  "ITGB1": { category: "Cell Adhesion", description: "Integrin subunit beta 1" },
  "ITK": { category: "Immune", description: "IL2 inducible T-cell kinase" },
  "JAK1": { category: "Signaling", description: "Janus kinase 1, JAK-STAT pathway" },
  "JAK2": { category: "Signaling", description: "Janus kinase 2, JAK-STAT pathway" },
  "KDM5A": { category: "Epigenetic", description: "Lysine demethylase 5A, histone demethylase" },
  "KDM6A": { category: "Epigenetic", description: "Lysine demethylase 6A, histone demethylase" },
  "KIT": { category: "Signaling", description: "KIT proto-oncogene, receptor tyrosine kinase" },
  "KMT2A": { category: "Epigenetic", description: "Lysine methyltransferase 2A, MLL1" },
  "KMT2D": { category: "Epigenetic", description: "Lysine methyltransferase 2D, MLL2" },
  "KRAS": { category: "Cancer", description: "Kirsten rat sarcoma viral oncogene, small GTPase" },
  "LAG3": { category: "Immune", description: "Lymphocyte activation gene 3, immune checkpoint" },
  "LAMA1": { category: "Extracellular Matrix", description: "Laminin subunit alpha 1" },
  "LATS1": { category: "Signaling", description: "Large tumor suppressor kinase 1, Hippo pathway" },
  "LATS2": { category: "Signaling", description: "Large tumor suppressor kinase 2, Hippo pathway" },
  "LCK": { category: "Immune", description: "LCK proto-oncogene, T-cell kinase" },
  "LCT": { category: "Digestion", description: "Lactase, lactose tolerance" },
  "LDHA": { category: "Metabolism", description: "Lactate dehydrogenase A, glycolysis" },
  "LDLR": { category: "Cardiovascular", description: "Low-density lipoprotein receptor" },
  "LEP": { category: "Hormone", description: "Leptin, obesity and metabolism" },
  "LIG4": { category: "DNA Repair", description: "DNA ligase 4, NHEJ" },
  "LIMK1": { category: "Signaling", description: "LIM domain kinase 1, actin dynamics" },
  "LRP5": { category: "Signaling", description: "LDL receptor related protein 5, WNT co-receptor" },
  "MAOA": { category: "Neurotransmitter", description: "Monoamine oxidase A, warrior gene" },
  "MAPK1": { category: "Signaling", description: "Mitogen-activated protein kinase 1, ERK2" },
  "MAPK3": { category: "Signaling", description: "Mitogen-activated protein kinase 3, ERK1" },
  "MASP1": { category: "Immune", description: "Mannose binding lectin serine peptidase 1, complement" },
  "MASP2": { category: "Immune", description: "Mannose binding lectin serine peptidase 2, complement" },
  "MC4R": { category: "Hormone", description: "Melanocortin 4 receptor, obesity" },
  "MDH2": { category: "Metabolism", description: "Malate dehydrogenase 2, TCA cycle" },
  "MDM2": { category: "Cell Cycle", description: "MDM2 proto-oncogene, p53 regulator" },
  "MDM4": { category: "Cell Cycle", description: "MDM4 p53 binding protein" },
  "MECP2": { category: "Epigenetic", description: "Methyl-CpG binding protein 2, Rett syndrome" },
  "MEN1": { category: "Cancer", description: "Menin 1, tumor suppressor" },
  "MET": { category: "Cancer", description: "MET proto-oncogene, receptor tyrosine kinase" },
  "MLH1": { category: "DNA Repair", description: "MutL homolog 1, mismatch repair" },
  "MOB1A": { category: "Signaling", description: "MOB kinase activator 1A, Hippo pathway" },
  "MSH2": { category: "DNA Repair", description: "MutS homolog 2, mismatch repair" },
  "MSH6": { category: "DNA Repair", description: "MutS homolog 6, mismatch repair" },
  "MTOR": { category: "Signaling", description: "Mechanistic target of rapamycin, growth control" },
  "MUTYH": { category: "DNA Repair", description: "MutY DNA glycosylase, base excision repair" },
  "MVD": { category: "Metabolism", description: "Mevalonate diphosphate decarboxylase, cholesterol" },
  "MVK": { category: "Metabolism", description: "Mevalonate kinase, cholesterol biosynthesis" },
  "MX1": { category: "Immune", description: "MX dynamin like GTPase 1, antiviral" },
  "MYBPC3": { category: "Muscle", description: "Myosin binding protein C3, cardiac" },
  "MYC": { category: "Cancer", description: "MYC proto-oncogene, transcription factor" },
  "NANOG": { category: "Development", description: "Nanog homeobox, pluripotency" },
  "NBN": { category: "DNA Repair", description: "Nibrin, double-strand break repair" },
  "NEIL1": { category: "DNA Repair", description: "Nei like DNA glycosylase 1, base excision repair" },
  "NF1": { category: "Cancer", description: "Neurofibromin 1, tumor suppressor, neurofibromatosis" },
  "NF2": { category: "Cancer", description: "Neurofibromin 2, merlin, tumor suppressor" },
  "NFKB1": { category: "Signaling", description: "Nuclear factor kappa B subunit 1, p50" },
  "NHEJ1": { category: "DNA Repair", description: "Non-homologous end-joining factor 1" },
  "NOG": { category: "Development", description: "Noggin, BMP antagonist" },
  "NOS3": { category: "Cardiovascular", description: "Nitric oxide synthase 3, endothelial" },
  "NOTCH1": { category: "Development", description: "Notch receptor 1, cell fate determination" },
  "NPC1": { category: "Metabolism", description: "NPC intracellular cholesterol transporter 1" },
  "NPC2": { category: "Metabolism", description: "NPC intracellular cholesterol transporter 2" },
  "NRAS": { category: "Signaling", description: "Neuroblastoma RAS viral oncogene, small GTPase" },
  "NRG1": { category: "Neurodevelopment", description: "Neuregulin 1, schizophrenia risk" },
  "NTRK1": { category: "Signaling", description: "Neurotrophic receptor tyrosine kinase 1, TrkA" },
  "NTRK2": { category: "Signaling", description: "Neurotrophic receptor tyrosine kinase 2, TrkB" },
  "NTRK3": { category: "Signaling", description: "Neurotrophic receptor tyrosine kinase 3, TrkC" },
  "OAS1": { category: "Immune", description: "2'-5'-oligoadenylate synthetase 1, antiviral" },
  "OGDH": { category: "Metabolism", description: "Oxoglutarate dehydrogenase, TCA cycle" },
  "OGG1": { category: "DNA Repair", description: "8-oxoguanine DNA glycosylase, base excision repair" },
  "OPN1LW": { category: "Vision", description: "Opsin 1 long wave sensitive, red cone" },
  "OPN1SW": { category: "Vision", description: "Opsin 1 short wave sensitive, blue cone" },
  "OR2J3": { category: "Sensory", description: "Olfactory receptor 2J3" },
  "PAK1": { category: "Signaling", description: "p21 activated kinase 1, Rho GTPase effector" },
  "PALB2": { category: "DNA Repair", description: "Partner and localizer of BRCA2" },
  "PARP1": { category: "DNA Repair", description: "Poly(ADP-ribose) polymerase 1" },
  "PARP2": { category: "DNA Repair", description: "Poly(ADP-ribose) polymerase 2" },
  "PAX6": { category: "Development", description: "Paired box 6, eye development" },
  "PBRM1": { category: "Epigenetic", description: "Polybromo 1, chromatin remodeling" },
  "PCK1": { category: "Metabolism", description: "Phosphoenolpyruvate carboxykinase 1, gluconeogenesis" },
  "PCK2": { category: "Metabolism", description: "Phosphoenolpyruvate carboxykinase 2, mitochondrial" },
  "PCSK9": { category: "Cardiovascular", description: "Proprotein convertase subtilisin/kexin type 9, cholesterol" },
  "PDCD1": { category: "Immune", description: "Programmed cell death 1, PD-1, immune checkpoint" },
  "PDGFRA": { category: "Signaling", description: "Platelet derived growth factor receptor alpha" },
  "PFKM": { category: "Metabolism", description: "Phosphofructokinase muscle, glycolysis" },
  "PGAM1": { category: "Metabolism", description: "Phosphoglycerate mutase 1, glycolysis" },
  "PGK1": { category: "Metabolism", description: "Phosphoglycerate kinase 1, glycolysis" },
  "PGK2": { category: "Metabolism", description: "Phosphoglycerate kinase 2, testis-specific" },
  "PIK3CA": { category: "Signaling", description: "Phosphatidylinositol-4,5-bisphosphate 3-kinase, PI3K" },
  "PINK1": { category: "Autophagy", description: "PTEN induced kinase 1, mitophagy" },
  "PKLR": { category: "Metabolism", description: "Pyruvate kinase liver and red blood cell" },
  "PKM": { category: "Metabolism", description: "Pyruvate kinase muscle, glycolysis" },
  "PMS2": { category: "DNA Repair", description: "PMS1 homolog 2, mismatch repair" },
  "PMVK": { category: "Metabolism", description: "Phosphomevalonate kinase, cholesterol" },
  "POLE": { category: "DNA Repair", description: "DNA polymerase epsilon, replication" },
  "POLR2A": { category: "Housekeeping", description: "RNA polymerase II subunit A" },
  "POU5F1": { category: "Development", description: "POU class 5 homeobox 1, OCT4, pluripotency" },
  "PPARG": { category: "Metabolism", description: "Peroxisome proliferator activated receptor gamma" },
  "PPIA": { category: "Housekeeping", description: "Peptidylprolyl isomerase A, cyclophilin A" },
  "PTEN": { category: "Cancer", description: "Phosphatase and tensin homolog, tumor suppressor" },
  "RAD50": { category: "DNA Repair", description: "RAD50 double strand break repair protein" },
  "RALA": { category: "Signaling", description: "RAS like proto-oncogene A" },
  "RALB": { category: "Signaling", description: "RAS like proto-oncogene B" },
  "RAP1A": { category: "Signaling", description: "RAP1A member of RAS oncogene family" },
  "RAP1B": { category: "Signaling", description: "RAP1B member of RAS oncogene family" },
  "RB1": { category: "Cell Cycle", description: "Retinoblastoma 1, tumor suppressor" },
  "RBL2": { category: "Cell Cycle", description: "RB transcriptional corepressor like 2, p130" },
  "RELA": { category: "Signaling", description: "RELA proto-oncogene, NF-kB p65 subunit" },
  "RELN": { category: "Neurodevelopment", description: "Reelin, neuronal migration" },
  "RET": { category: "Signaling", description: "Ret proto-oncogene, receptor tyrosine kinase" },
  "RHEB": { category: "Signaling", description: "Ras homolog mTORC1 binding, mTOR activator" },
  "RHOA": { category: "Signaling", description: "Ras homolog family member A, small GTPase" },
  "RHOB": { category: "Signaling", description: "Ras homolog family member B" },
  "RHOC": { category: "Signaling", description: "Ras homolog family member C" },
  "RICTOR": { category: "Signaling", description: "RPTOR independent companion of mTOR, mTORC2" },
  "ROCK1": { category: "Signaling", description: "Rho associated coiled-coil kinase 1" },
  "ROCK2": { category: "Signaling", description: "Rho associated coiled-coil kinase 2" },
  "ROS1": { category: "Cancer", description: "ROS proto-oncogene 1, receptor tyrosine kinase" },
  "RPL4": { category: "Housekeeping", description: "Ribosomal protein L4" },
  "RPS3": { category: "Housekeeping", description: "Ribosomal protein S3" },
  "RPTOR": { category: "Signaling", description: "Regulatory associated protein of mTOR, mTORC1" },
  "RRAS": { category: "Signaling", description: "RAS related protein" },
  "RRAS2": { category: "Signaling", description: "RAS related protein 2" },
  "SAV1": { category: "Signaling", description: "Salvador family WW domain containing 1, Hippo pathway" },
  "SC5D": { category: "Metabolism", description: "Sterol-C5-desaturase, cholesterol biosynthesis" },
  "SCD": { category: "Metabolism", description: "Stearoyl-CoA desaturase, fatty acid synthesis" },
  "SDHAF2": { category: "Metabolism", description: "Succinate dehydrogenase assembly factor 2" },
  "SDHB": { category: "Metabolism", description: "Succinate dehydrogenase complex subunit B" },
  "SDHC": { category: "Metabolism", description: "Succinate dehydrogenase complex subunit C" },
  "SDHD": { category: "Metabolism", description: "Succinate dehydrogenase complex subunit D" },
  "SETD2": { category: "Epigenetic", description: "SET domain containing 2, histone methyltransferase" },
  "SFRP1": { category: "Signaling", description: "Secreted frizzled related protein 1, WNT inhibitor" },
  "SHANK3": { category: "Neurodevelopment", description: "SH3 and ankyrin domain containing 3, autism" },
  "SHH": { category: "Development", description: "Sonic hedgehog signaling molecule" },
  "SIRT1": { category: "Epigenetic", description: "Sirtuin 1, NAD-dependent deacetylase" },
  "SIRT2": { category: "Epigenetic", description: "Sirtuin 2, NAD-dependent deacetylase" },
  "SLC6A4": { category: "Neurotransmitter", description: "Solute carrier family 6 member 4, serotonin transporter" },
  "SMAD2": { category: "Signaling", description: "SMAD family member 2, TGF-beta pathway" },
  "SMAD3": { category: "Signaling", description: "SMAD family member 3, TGF-beta pathway" },
  "SMAD4": { category: "Signaling", description: "SMAD family member 4, TGF-beta pathway" },
  "SMARCA4": { category: "Epigenetic", description: "SWI/SNF related chromatin remodeling, BRG1" },
  "SNCA": { category: "Neurological", description: "Synuclein alpha, Parkinson's disease" },
  "SOAT1": { category: "Metabolism", description: "Sterol O-acyltransferase 1, cholesterol esterification" },
  "SOCS1": { category: "Signaling", description: "Suppressor of cytokine signaling 1, JAK-STAT inhibitor" },
  "SOS1": { category: "Signaling", description: "SOS Ras/Rac guanine nucleotide exchange factor 1" },
  "SOX2": { category: "Development", description: "SRY-box transcription factor 2, stem cells" },
  "SQLE": { category: "Metabolism", description: "Squalene epoxidase, cholesterol biosynthesis" },
  "SQSTM1": { category: "Autophagy", description: "Sequestosome 1, p62, autophagy receptor" },
  "STAT3": { category: "Signaling", description: "Signal transducer and activator of transcription 3" },
  "STAT5A": { category: "Signaling", description: "Signal transducer and activator of transcription 5A" },
  "STK11": { category: "Cancer", description: "Serine/threonine kinase 11, LKB1, tumor suppressor" },
  "SUCLA2": { category: "Metabolism", description: "Succinate-CoA ligase subunit alpha, TCA cycle" },
  "SUCLG1": { category: "Metabolism", description: "Succinate-CoA ligase subunit alpha, TCA cycle" },
  "SYK": { category: "Immune", description: "Spleen associated tyrosine kinase" },
  "TALDO1": { category: "Metabolism", description: "Transaldolase 1, pentose phosphate pathway" },
  "TAS2R38": { category: "Sensory", description: "Taste 2 receptor member 38, bitter taste, PTC" },
  "TBX5": { category: "Development", description: "T-box transcription factor 5, heart/limb development" },
  "TEAD1": { category: "Signaling", description: "TEA domain transcription factor 1, Hippo pathway" },
  "TET2": { category: "Epigenetic", description: "Tet methylcytosine dioxygenase 2, DNA demethylation" },
  "TGFB1": { category: "Signaling", description: "Transforming growth factor beta 1" },
  "TGFBR1": { category: "Signaling", description: "TGF-beta receptor 1" },
  "TGFBR2": { category: "Signaling", description: "TGF-beta receptor 2" },
  "TIGIT": { category: "Immune", description: "T-cell immunoreceptor with Ig and ITIM domains, checkpoint" },
  "TKT": { category: "Metabolism", description: "Transketolase, pentose phosphate pathway" },
  "TNF": { category: "Immune", description: "Tumor necrosis factor, inflammatory cytokine" },
  "TNNT2": { category: "Muscle", description: "Troponin T2, cardiac" },
  "TP53": { category: "Cancer", description: "Tumor protein p53, guardian of the genome" },
  "TP53BP1": { category: "DNA Repair", description: "Tumor protein p53 binding protein 1" },
  "TP63": { category: "Development", description: "Tumor protein p63, p53 family" },
  "TP73": { category: "Development", description: "Tumor protein p73, p53 family" },
  "TPI1": { category: "Metabolism", description: "Triosephosphate isomerase 1, glycolysis" },
  "TRIM5": { category: "Immune", description: "Tripartite motif containing 5, retroviral restriction" },
  "TSC1": { category: "Signaling", description: "Tuberous sclerosis 1, hamartin, mTOR inhibitor" },
  "TSC2": { category: "Signaling", description: "Tuberous sclerosis 2, tuberin, mTOR inhibitor" },
  "TUBA1A": { category: "Housekeeping", description: "Tubulin alpha 1A, microtubule" },
  "TUBB": { category: "Housekeeping", description: "Tubulin beta, microtubule" },
  "VCP": { category: "Housekeeping", description: "Valosin containing protein, p97, ATPase" },
  "VEGFA": { category: "Signaling", description: "Vascular endothelial growth factor A, angiogenesis" },
  "VHL": { category: "Cancer", description: "Von Hippel-Lindau tumor suppressor, HIF regulator" },
  "WNT1": { category: "Signaling", description: "Wnt family member 1" },
  "WNT3A": { category: "Signaling", description: "Wnt family member 3A" },
  "XRCC1": { category: "DNA Repair", description: "X-ray repair cross complementing 1, base excision repair" },
  "XRCC2": { category: "DNA Repair", description: "X-ray repair cross complementing 2, homologous recombination" },
  "XRCC3": { category: "DNA Repair", description: "X-ray repair cross complementing 3, homologous recombination" },
  "XRCC4": { category: "DNA Repair", description: "X-ray repair cross complementing 4, NHEJ" },
  "YAP1": { category: "Signaling", description: "Yes1 associated transcriptional regulator, Hippo pathway" },
  "YWHAZ": { category: "Housekeeping", description: "14-3-3 protein zeta/delta, scaffolding protein" },
  "ZP2": { category: "Reproduction", description: "Zona pellucida glycoprotein 2, egg coat" },
  "ZP3": { category: "Reproduction", description: "Zona pellucida glycoprotein 3, sperm binding" },
  "ZRANB3": { category: "DNA Repair", description: "Zinc finger RANBP2-type containing 3, replication stress response" }
};

// Helper function to get just the gene names (for backward compatibility)
export const getGeneNames = () => Object.keys(genes);

// Helper function to get genes by category
export const getGenesByCategory = (category) => {
  return Object.entries(genes)
    .filter(([_, data]) => data.category === category)
    .map(([name, _]) => name);
};

// Helper function to get all unique categories
export const getCategories = () => {
  const categories = new Set(Object.values(genes).map(g => g.category));
  return Array.from(categories).sort();
};
